In [1]:
import pandas as pd
path = r"C:\Users\ashle\OneDrive\Desktop\UManitoba\Courses\FALL 2026\COMP 3380\GroupProject\DataCleaning\cast.csv"

In [2]:
bad_lines = []

def catch_bad_line(line):
    bad_lines.append(line)
    return None

df = pd.read_csv(path, engine='python', on_bad_lines=catch_bad_line)

In [3]:
print(f"Loaded {len(df)} valid rows.")
print(f"Captured {len(bad_lines)} malformed rows for cleaning.")
# Print out the data
df

Loaded 150044 valid rows.
Captured 0 malformed rows for cleaning.

,id,movie_id,person_id,name,character,cast_order,movie_title,movie_release_date
0,64660,2,54768,Turo Pajala,Taisto Kasurinen,0,Ariel,1988-10-21
1,64661,2,54769,Susanna Haavisto,Irmeli Pihlaja,1,Ariel,1988-10-21
2,64662,2,4826,Matti Pellonpää,Mikkonen,2,Ariel,1988-10-21
3,64663,2,54770,Eetu Hilkamo,Riku,3,Ariel,1988-10-21
4,64664,2,1177496,Erkki Pajala,Miner,4,Ariel,1988-10-21
...,...,...,...,...,...,...,...,...
150039,73207,1630155,592476,Marian Álvarez,NaN,4,Antes,2026-02-06
150040,73208,1630155,51905,Andrés Gertrúdix,NaN,5,Antes,2026-02-06
150041,73209,1630155,1787126,Pilar Gómez,NaN,6,Antes,2026-02-06
150042,73210,1630155,105161,Emilio Gutiérrez Caba,NaN,7,Antes,2026-02-06
150043,73211,1630155,1042765,Arturo Valls,NaN,8,Antes,2026-02-06

In [4]:
# Data overview
df.info()
print("Data types seems to be consistent and there are no null values.")

print("Duplicate rows count:", df.duplicated().sum())

<class 'pandas.DataFrame'>
RangeIndex: 150044 entries, 0 to 150043
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   id                  150044 non-null  int64
 1   movie_id            150044 non-null  int64
 2   person_id           150044 non-null  int64
 3   name                150044 non-null  str
 4   character           142822 non-null  str
 5   cast_order          150044 non-null  int64
 6   movie_title         150044 non-null  str
 7   movie_release_date  149751 non-null  str
dtypes: int64(4), str(4)
memory usage: 9.2 MB
Data types seems to be consistent and there are no null values.
Duplicate rows count: 0

In [5]:
# Data cleaning start
# 1. TODO: NaN values

print("Sum of NaN values:")
sumOfNaNValues = df.isna().sum()
sumOfNaNValues

Sum of NaN values:

id                       0
movie_id                 0
person_id                0
name                     0
character             7222
cast_order               0
movie_title              0
movie_release_date     293
dtype: int64

In [6]:
print("From here, there are 7222 NaN values from Character")
df['character'] = df['character'].fillna('Unknown') #Fill the NaN values to 'unknown' for now.

From here, there are 7222 NaN values from Character

In [7]:
# 2. Drop columns that we don't need from ER diagram

# In the ER diagram, cast (Person) entity only has 4 attributes: personID, personName, castOrder, and character.
# Since we'll need a connection to movie, movie_id would be enough
df = df.drop(columns=['movie_title','movie_release_date'])
df

,id,movie_id,person_id,name,character,cast_order
0,64660,2,54768,Turo Pajala,Taisto Kasurinen,0
1,64661,2,54769,Susanna Haavisto,Irmeli Pihlaja,1
2,64662,2,4826,Matti Pellonpää,Mikkonen,2
3,64663,2,54770,Eetu Hilkamo,Riku,3
4,64664,2,1177496,Erkki Pajala,Miner,4
...,...,...,...,...,...,...
150039,73207,1630155,592476,Marian Álvarez,Unknown,4
150040,73208,1630155,51905,Andrés Gertrúdix,Unknown,5
150041,73209,1630155,1787126,Pilar Gómez,Unknown,6
150042,73210,1630155,105161,Emilio Gutiérrez Caba,Unknown,7
150043,73211,1630155,1042765,Arturo Valls,Unknown,8

In [8]:
# 3. String format: Trailing whitespace
# Identify rows with two or more consecutive spaces
df_inconsistentWhitespace = df[df['name'].str.contains(r'\s{2,}', regex=True, na=False)]
df_inconsistentWhitespace[['id', 'name']]

            id                      name
64779    26197             Faysal  Ahmed
76646    90556            Izzie  Galanti
76664   119196       Jorge de los Reyes
82691   144260             Hans  Weicker
99785   131998            Álvaro  Mamute
114226  108902  Jonathan  Aidan Cockrell
116974  103705            Judith  Gailer
122291  112222            Keren  Kraizer
139390     433        Luke Jai  McIntosh

In [9]:
# Strip leading/trailing spaces, then collapse multiple internal spaces into a single space
df['name'] = df['name'].str.strip().str.replace(r'\s+', ' ', regex=True)

# Confirm leading whitespace has been cleaned
df_inconsistentWhitespace = df[df['name'].str.contains(r'\s{2,}', regex=True, na=False)]
df_inconsistentWhitespace[['id', 'name']]

Empty DataFrame
Columns: [id, name]
Index: []

In [ ]:
# 4.

In [10]:
# Print Cleaned up data
df

,id,movie_id,person_id,name,character,cast_order
0,64660,2,54768,Turo Pajala,Taisto Kasurinen,0
1,64661,2,54769,Susanna Haavisto,Irmeli Pihlaja,1
2,64662,2,4826,Matti Pellonpää,Mikkonen,2
3,64663,2,54770,Eetu Hilkamo,Riku,3
4,64664,2,1177496,Erkki Pajala,Miner,4
...,...,...,...,...,...,...
150039,73207,1630155,592476,Marian Álvarez,Unknown,4
150040,73208,1630155,51905,Andrés Gertrúdix,Unknown,5
150041,73209,1630155,1787126,Pilar Gómez,Unknown,6
150042,73210,1630155,105161,Emilio Gutiérrez Caba,Unknown,7
150043,73211,1630155,1042765,Arturo Valls,Unknown,8

In [11]:
# Filter df view to not include Unknown characters
df_filtered = df.loc[df['character'] != 'Unknown']
df_filtered

,id,movie_id,person_id,name,character,cast_order
0,64660,2,54768,Turo Pajala,Taisto Kasurinen,0
1,64661,2,54769,Susanna Haavisto,Irmeli Pihlaja,1
2,64662,2,4826,Matti Pellonpää,Mikkonen,2
3,64663,2,54770,Eetu Hilkamo,Riku,3
4,64664,2,1177496,Erkki Pajala,Miner,4
...,...,...,...,...,...,...
150025,104713,1627792,3857648,Ralmon Mendoza,Kenji,3
150026,104714,1627792,5981215,Kurt Veneracion,Niko,4
150027,104715,1627792,4908172,Trish Gaden,Jamie,5
150028,104716,1627792,5998241,Michael Daulogas,Boss Mike,6
150029,104717,1627792,5998243,Jordan Alejandrino,Mark,7