In [1]:
import pandas as pd

In [2]:
path = r"C:\Users\ashle\OneDrive\Desktop\UManitoba\Courses\FALL 2026\COMP 3380\GroupProject\DataCleaning\movies.csv"

In [3]:
bad_lines = []

def catch_bad_line(line):
    bad_lines.append(line)
    return None

In [4]:
df = pd.read_csv(path, engine='python', on_bad_lines=catch_bad_line)

In [5]:
print(f"Loaded {len(df)} valid rows.")
print(f"Captured {len(bad_lines)} malformed rows for cleaning.")

Loaded 9771 valid rows.
Captured 0 malformed rows for cleaning.

In [6]:
# Print out the table
df

,id,title,original_title,overview,release_date,runtime,budget,revenue,vote_average,vote_count,...,backdrop_path,status,tagline,homepage,original_language,adult,video,created_at,updated_at,genres
0,2,Ariel,Ariel,A Finnish man goes to the city to find a job a...,1988-10-21,73.0,0.0,0.0,7.102,368,...,/hQ4pYsIbP22TMXOUdSfC2mjWrO0.jpg,Released,NaN,NaN,fi,0,0,2026-02-13 12:09:05,2026-02-13T17:39:05.734678,"Drama,Comedy,Crime,Romance"
1,11,Star Wars,Star Wars,Princess Leia is captured and held hostage by ...,1977-05-25,121.0,11000000.0,775398007.0,8.202,21922,...,/2w4xG178RpB4MDAIfTkqAuSJzec.jpg,Released,"A long time ago in a galaxy far, far away...",http://www.starwars.com/films/star-wars-episod...,en,0,0,2026-02-13 10:49:07,2026-02-13T16:19:07.277805,"Adventure,Action,Science Fiction"
2,12,Finding Nemo,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",2003-05-30,100.0,94000000.0,940335536.0,7.817,20256,...,/eCynaAOgYYiw5yN5lBwz3IxqvaW.jpg,Released,There are 3.7 trillion fish in the ocean. They...,http://movies.disney.com/finding-nemo,en,0,0,2026-02-13 10:52:41,2026-02-13T16:22:41.330322,"Animation,Family"
3,13,Forrest Gump,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,142.0,55000000.0,677387716.0,8.462,29226,...,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,Released,The world will never be the same once you've s...,https://www.paramountmovies.com/movies/forrest...,en,0,0,2026-02-13 10:49:10,2026-02-13T16:19:10.070631,"Drama,Comedy,Romance"
4,14,American Beauty,American Beauty,"Lester Burnham, a depressed suburban father in...",1999-09-15,122.0,15000000.0,356296601.0,8.002,12792,...,/2ndw55F40IkALzWyjCCza3M6nqM.jpg,Released,... look closer,NaN,en,0,0,2026-02-13 11:14:17,2026-02-13T16:44:17.072753,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9766,1618945,Yoh! Bestie,Yoh! Bestie,"Thando is perpetually unlucky in love, but whe...",2026-02-06,95.0,0.0,0.0,6.136,22,...,/1EVHnzF3gescyQZSqwbx5LfQ1EN.jpg,Released,NaN,NaN,en,0,0,2026-02-13 10:47:02,2026-02-13T16:17:02.176004,"Comedy,Romance"
9767,1620991,The Investigation of Lucy Letby,The Investigation of Lucy Letby,An engaging and thought-provoking look at Lucy...,2026-02-04,95.0,0.0,0.0,6.45,20,...,/qhSfXdkrIzwYsyQ3Z9ehFmO3zjy.jpg,Released,NaN,https://www.netflix.com/title/81719673,en,0,0,2026-02-13 10:53:57,2026-02-13T16:23:57.411258,"Crime,Documentary"
9768,1627792,Sagaran,Sagaran,As female motorcycle racer Mica and her mechan...,2026-02-06,70.0,0.0,0.0,0.0,0,...,/mwEai7501xFLP6DKaAEZScZuIgB.jpg,Released,NaN,NaN,tl,0,0,2026-02-13 13:05:36,2026-02-13T18:35:36.168808,Drama
9769,1627796,Pansamantala,Pansamantala,A story of a drunken dare that pulls best frie...,2026-02-13,0.0,0.0,0.0,0.0,0,...,/bzKjJboSsOA6sKthmNN5ojM01vw.jpg,Released,NaN,NaN,tl,0,0,2026-02-13 11:42:56,2026-02-13T17:12:56.467912,Drama
9770,1630155,Antes,Antes,NaN,2026-02-06,0.0,0.0,0.0,4.0,1,...,NaN,Released,NaN,NaN,es,0,0,2026-02-13 12:20:14,2026-02-13T17:50:14.858738,NaN

In [11]:
# Technical jargon: deduplication
df = df.drop_duplicates(subset=['id'], keep='first')
df

,id,title,original_title,overview,release_date,runtime,budget,revenue,vote_average,vote_count,...,backdrop_path,status,tagline,homepage,original_language,adult,video,created_at,updated_at,genres
0,2,Ariel,Ariel,A Finnish man goes to the city to find a job a...,1988-10-21,73.0,0.0,0.0,7.102,368,...,/hQ4pYsIbP22TMXOUdSfC2mjWrO0.jpg,Released,NaN,NaN,fi,0,0,2026-02-13 12:09:05,2026-02-13T17:39:05.734678,"Drama,Comedy,Crime,Romance"
1,11,Star Wars,Star Wars,Princess Leia is captured and held hostage by ...,1977-05-25,121.0,11000000.0,775398007.0,8.202,21922,...,/2w4xG178RpB4MDAIfTkqAuSJzec.jpg,Released,"A long time ago in a galaxy far, far away...",http://www.starwars.com/films/star-wars-episod...,en,0,0,2026-02-13 10:49:07,2026-02-13T16:19:07.277805,"Adventure,Action,Science Fiction"
2,12,Finding Nemo,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",2003-05-30,100.0,94000000.0,940335536.0,7.817,20256,...,/eCynaAOgYYiw5yN5lBwz3IxqvaW.jpg,Released,There are 3.7 trillion fish in the ocean. They...,http://movies.disney.com/finding-nemo,en,0,0,2026-02-13 10:52:41,2026-02-13T16:22:41.330322,"Animation,Family"
3,13,Forrest Gump,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,142.0,55000000.0,677387716.0,8.462,29226,...,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,Released,The world will never be the same once you've s...,https://www.paramountmovies.com/movies/forrest...,en,0,0,2026-02-13 10:49:10,2026-02-13T16:19:10.070631,"Drama,Comedy,Romance"
4,14,American Beauty,American Beauty,"Lester Burnham, a depressed suburban father in...",1999-09-15,122.0,15000000.0,356296601.0,8.002,12792,...,/2ndw55F40IkALzWyjCCza3M6nqM.jpg,Released,... look closer,NaN,en,0,0,2026-02-13 11:14:17,2026-02-13T16:44:17.072753,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9766,1618945,Yoh! Bestie,Yoh! Bestie,"Thando is perpetually unlucky in love, but whe...",2026-02-06,95.0,0.0,0.0,6.136,22,...,/1EVHnzF3gescyQZSqwbx5LfQ1EN.jpg,Released,NaN,NaN,en,0,0,2026-02-13 10:47:02,2026-02-13T16:17:02.176004,"Comedy,Romance"
9767,1620991,The Investigation of Lucy Letby,The Investigation of Lucy Letby,An engaging and thought-provoking look at Lucy...,2026-02-04,95.0,0.0,0.0,6.45,20,...,/qhSfXdkrIzwYsyQ3Z9ehFmO3zjy.jpg,Released,NaN,https://www.netflix.com/title/81719673,en,0,0,2026-02-13 10:53:57,2026-02-13T16:23:57.411258,"Crime,Documentary"
9768,1627792,Sagaran,Sagaran,As female motorcycle racer Mica and her mechan...,2026-02-06,70.0,0.0,0.0,0.0,0,...,/mwEai7501xFLP6DKaAEZScZuIgB.jpg,Released,NaN,NaN,tl,0,0,2026-02-13 13:05:36,2026-02-13T18:35:36.168808,Drama
9769,1627796,Pansamantala,Pansamantala,A story of a drunken dare that pulls best frie...,2026-02-13,0.0,0.0,0.0,0.0,0,...,/bzKjJboSsOA6sKthmNN5ojM01vw.jpg,Released,NaN,NaN,tl,0,0,2026-02-13 11:42:56,2026-02-13T17:12:56.467912,Drama
9770,1630155,Antes,Antes,NaN,2026-02-06,0.0,0.0,0.0,4.0,1,...,NaN,Released,NaN,NaN,es,0,0,2026-02-13 12:20:14,2026-02-13T17:50:14.858738,NaN

In [15]:
# Technical jargon: imputation (filling values) and null handling
# Drop rows where critical fields are missing
df = df.dropna(subset=['title', 'release_date'])

# Impute non-critical text fields
df['overview'] = df['overview'].fillna('No overview available')
df['tagline'] = df['tagline'].fillna('No tagline available')
df['homepage'] = df['homepage'].fillna('No homepage available')
df['genres'] = df['genres'].fillna('No genres available')
df

,id,title,original_title,overview,release_date,runtime,budget,revenue,vote_average,vote_count,...,backdrop_path,status,tagline,homepage,original_language,adult,video,created_at,updated_at,genres
0,2,Ariel,Ariel,A Finnish man goes to the city to find a job a...,1988-10-21,73.0,0.0,0.0,7.102,368,...,/hQ4pYsIbP22TMXOUdSfC2mjWrO0.jpg,Released,No tagline available,No homepage available,fi,0,0,2026-02-13 12:09:05,2026-02-13T17:39:05.734678,"Drama,Comedy,Crime,Romance"
1,11,Star Wars,Star Wars,Princess Leia is captured and held hostage by ...,1977-05-25,121.0,11000000.0,775398007.0,8.202,21922,...,/2w4xG178RpB4MDAIfTkqAuSJzec.jpg,Released,"A long time ago in a galaxy far, far away...",http://www.starwars.com/films/star-wars-episod...,en,0,0,2026-02-13 10:49:07,2026-02-13T16:19:07.277805,"Adventure,Action,Science Fiction"
2,12,Finding Nemo,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",2003-05-30,100.0,94000000.0,940335536.0,7.817,20256,...,/eCynaAOgYYiw5yN5lBwz3IxqvaW.jpg,Released,There are 3.7 trillion fish in the ocean. They...,http://movies.disney.com/finding-nemo,en,0,0,2026-02-13 10:52:41,2026-02-13T16:22:41.330322,"Animation,Family"
3,13,Forrest Gump,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,142.0,55000000.0,677387716.0,8.462,29226,...,/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg,Released,The world will never be the same once you've s...,https://www.paramountmovies.com/movies/forrest...,en,0,0,2026-02-13 10:49:10,2026-02-13T16:19:10.070631,"Drama,Comedy,Romance"
4,14,American Beauty,American Beauty,"Lester Burnham, a depressed suburban father in...",1999-09-15,122.0,15000000.0,356296601.0,8.002,12792,...,/2ndw55F40IkALzWyjCCza3M6nqM.jpg,Released,... look closer,No homepage available,en,0,0,2026-02-13 11:14:17,2026-02-13T16:44:17.072753,Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9766,1618945,Yoh! Bestie,Yoh! Bestie,"Thando is perpetually unlucky in love, but whe...",2026-02-06,95.0,0.0,0.0,6.136,22,...,/1EVHnzF3gescyQZSqwbx5LfQ1EN.jpg,Released,No tagline available,No homepage available,en,0,0,2026-02-13 10:47:02,2026-02-13T16:17:02.176004,"Comedy,Romance"
9767,1620991,The Investigation of Lucy Letby,The Investigation of Lucy Letby,An engaging and thought-provoking look at Lucy...,2026-02-04,95.0,0.0,0.0,6.45,20,...,/qhSfXdkrIzwYsyQ3Z9ehFmO3zjy.jpg,Released,No tagline available,https://www.netflix.com/title/81719673,en,0,0,2026-02-13 10:53:57,2026-02-13T16:23:57.411258,"Crime,Documentary"
9768,1627792,Sagaran,Sagaran,As female motorcycle racer Mica and her mechan...,2026-02-06,70.0,0.0,0.0,0.0,0,...,/mwEai7501xFLP6DKaAEZScZuIgB.jpg,Released,No tagline available,No homepage available,tl,0,0,2026-02-13 13:05:36,2026-02-13T18:35:36.168808,Drama
9769,1627796,Pansamantala,Pansamantala,A story of a drunken dare that pulls best frie...,2026-02-13,0.0,0.0,0.0,0.0,0,...,/bzKjJboSsOA6sKthmNN5ojM01vw.jpg,Released,No tagline available,No homepage available,tl,0,0,2026-02-13 11:42:56,2026-02-13T17:12:56.467912,Drama
9770,1630155,Antes,Antes,No overview available,2026-02-06,0.0,0.0,0.0,4.0,1,...,NaN,Released,No tagline available,No homepage available,es,0,0,2026-02-13 12:20:14,2026-02-13T17:50:14.858738,No genres available